### ISSUE TITLE
Redux State Issue

### ISSUE THREAD

**Issue by jdevries3133** [jdevries3133/song_maker_gallery#15]
When a user navigates to a gallery whose name does not match the gallery in the redux state already, redux state should be flushed so that a loading spinner appears instead of the previously viewed gallery.

Because this does not happen currently, a user who visits a second gallery will see the gallery they navigated to previously until the useEffect hook is evaluated, redux state is updated with new data, and the gallery completely changes and re-renders.

**Comment by hedgerh** [comment]
Option 1. Return loading component `if (this.props.status === undefined || this.props.gallery.id === this.state.slug) {` if gallery has an id matching slug.

Option 2. Don't return gallery from `mapStateToProps` if the id doesn't match `state.slug`.

Option 3. Store galleries in your state as an object by id, like `{ 123: { title: 'foo', id: 123 }, 234: { title: 'bar', id: 234 } }`. Then select the gallery from state with `this.state.slug`. It should be undefined until the new gallery returns.

Something like those should work.

**Comment by jdevries3133** [comment]
Thank you @hedgerh, Option 2 sounds like a perfect solution. I'm going to try to implement it now.

**Comment by jdevries3133** [comment]
Option 2 implemented! Thanks again :)
