### ISSUE TITLE
Create <EditableRichTile />

### ISSUE THREAD

**Issue by jdevries3133** [jdevries3133/song_maker_gallery#44]
Part of #34 project. See #34 for wireframe.

**Comment by mmulet** [comment]
I saw the help wanted tag, so I created a code relay task for this here: https://github.com/code-relay-io/song_maker_gallery/blob/main/README.md . So, we will work on this.

**Comment by jdevries3133** [comment]
@mmulet I hope someone would jump in on this, that would be fantastic! If anyone sees this, I just finished setting up storybook in my latest commit, so that should make developing this component in isolation a breeze if you want to take it on.

**Comment by mmulet** [comment]
@jdevries3133 Great! We've had one commit already, they said the storybook and CONTRIBUTING.md were very helpful!
Code relay just started so we don't have a lot of users right now, so I can't say how fast we'll finish the issue, but I will send javascript/react programmers to this issue as they come in.

**Comment by jdevries3133** [comment]
@mmulet  Awesome well, there is no rush and I really appreciate the help. I still need to do all the other components in that wireframe + backend implementation, etc, so it will be a while before this issue is hanging anything up.

It's funny that I got storybook set up around the same exact time you came to help – very serendipitous!

I'm glad the contributing guide was helpful I updated it (slightly) and it also now references some new details on how to implement the wireframes which lives in the thread for #34.

Thanks again!

**Comment by jdevries3133** [comment]
@mmulet can I get a PR on what has been done so far? I know it's just a little setup work, but at least it'll get the contributor into the commit history.

As you can see, I'm wrapping up on these wireframes so I'm getting to the point of wanting to move forward with this.

**Comment by mmulet** [comment]
Sorry to take so long to get back to you. We've had one commit so far, sorry that it's so slow, we'll still growing. 
Everything is here: https://github.com/code-relay-io/song_maker_gallery/blob/main/README.md

**Comment by jdevries3133** [comment]
@mmulet that's ok! I went ahead and pulled your commit in to this repo. For future contributors on your fork, they should be sure to pull from upstream because I keep making changes to this part of the project as I work on the gallery form (#41)
